version: '3.0'

services:

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx
    restart: unless-stopped

networks:
  nginx:
    driver: bridge
